### ISSUE TITLE
LegacyFactions chat hook

### ISSUE THREAD

**Issue by Androkai** [redstone/LegacyFactions#198]
Hi guys,

seems like LegacyFactions is canceling all chat events like the old Factions from drtshock for which you can find [6 issue reports](https://github.com/drtshock/Factions/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20cancel) about. The problem is that because of this every other chat related plugin needs to ignore the canceling state (results in private messages being shown) or respect it (results in no messages being shown) which is bad. Also I can't find some kind of onPlayerChatEvent to probably hook into.

Can you help?

**Comment by MarkehMe** [comment]
Hi! 

This only happens if chatTagRelationalOverride is true. You can see on the wiki:

https://github.com/redstone/LegacyFactions/wiki/Expansion:-FactionsChat

There is a warning about using this configuration option 

I could also add an event for Faction chatting. 

What are you trying to do?

**Comment by Androkai** [comment]
I'm supporting the work on the "[DiscordSRV](https://github.com/Scarsz/DiscordSRV)" plugin by Scarsz, a Discord - Minecraft bridge. Yesterday we had a player asking for help connecting LegacyFactions chat with Discord. We already knew the mentioned incompatibility for drtshock's Factions but it was the first time I heard about your fork who appears to be much better maintained. After we found out that it was the canceling state of the messages again, I searched the wiki a little bit and took a look at the API, but couldn't find anything quickly and so I contacted you this way.

As far as I know, Factions has the global and an admin channel where it would make sense to hook into. The other ones aren't fixed. Do you think it makes sense to have a hook on our side for Factions?

**Comment by MarkehMe** [comment]
No worries, if you wanna jump on our discord and throw some questions my way feel free to (https://discord.gg/Fw6bwGA)

I'm not sure of how to add integration from my end though. 

Let me give you a run down on what LegacyFactions is doing!  😄  I know how confusing it can be to look through large projects and try to understand what is going on.

By default, we only remove recipients:
https://github.com/redstone/LegacyFactions/blob/2cd5f9197b977100420443c5f4618cfb10b9fe32/src/main/java/net/redstoneore/legacyfactions/expansion/chat/FactionsChatListener.java#L48-L55

And format:

https://github.com/redstone/LegacyFactions/blob/2cd5f9197b977100420443c5f4618cfb10b9fe32/src/main/java/net/redstoneore/legacyfactions/expansion/chat/FactionsChatListener.java#L117

But as some of the servers operators want it so it has relational colours. We have placeholders for people to do this in chat plugins - but as not many chat plugins do this we actually offered this configuration option:

https://github.com/redstone/LegacyFactions/wiki/Expansion:-FactionsChat#chattagrelationaloverride 

> `chattagrelationaloverride`
> You really shouldn't use this. It cancels the chat event, replaces relational placeholders, and then sends it to players manually. Your chat plugin should handle relational placeholders for you, but if not - enable this.

Which is my nice way of saying: factions shouldn't do this 😆 , but if you really want it (some people _really_ wanted the relational colours) you can enable it. 

You can find this here:
https://github.com/redstone/LegacyFactions/blob/2cd5f9197b977100420443c5f4618cfb10b9fe32/src/main/java/net/redstoneore/legacyfactions/expansion/chat/FactionsChatListener.java#L157-L174

I don't mind adding the support myself. I'm just trying to think of how it would be implemented. Because it doesn't really make sense to add faction/alliance chat to discord. But for public chat it makes sense! Perhaps adding a hook into discord @ `chatOverride` if the sender is in public chat? 

Sorry for information overload - what do you think?

**Comment by MarkehMe** [comment]
Added event `EventFactionsChat` for v1.5.0

**Comment by MarkehMe** [comment]
Okay.

https://github.com/Scarsz/DiscordSRV/blob/7d5ff8dc8bb84f0a829207ee031be511c2c5423c/src/main/java/github/scarsz/discordsrv/DiscordSRV.java#L617

They will need to check if the player (by using FPlayer) is not in public chat here. Please ask the developers to add support from their end. Feel free to have them reach out to me for help! 

Thanks!
