### ISSUE TITLE
Faction Relation Placeholders error

### ISSUE THREAD

**Issue by DuckCraftPvP** [redstone/LegacyFactions#212]
http://prntscr.com/gkvqq4
My name is duckcraftpvp, Star_Destroyer48's faction tag should be red not green and mine should be green not red. Please fix.

**Comment by DuckCraftPvP** [comment]
colours seem backwards

**Comment by MarkehMe** [comment]
Hello! 😄  

This is a friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf` file! Put it on www.pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks**

*This is an automatic message! Please respond saying you have done these things.*

**Comment by DuckCraftPvP** [comment]
https://hastebin.com/yeziwodeho.md | F debug
This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

https://hastebin.com/sipefifino.json | Config

**Comment by MarkehMe** [comment]
Thanks for the info! What is the relation between duckcraftpvp and Star_Destroyer48?

**Comment by DuckCraftPvP** [comment]
enemy

**Comment by MarkehMe** [comment]
I can't replicate this.

Can you please double check that they are **both** set to enemy each other - as this is the only way for a relation to show properly.

**Comment by DuckCraftPvP** [comment]
Only 1 should have to enemy the other, Thats dumb if they both gotta enemy each other and il check later on as i half stopped dev on my server.

**Comment by MarkehMe** [comment]
This is normal. Otherwise it is called a **relationship wish**.

**Comment by jds110** [comment]
When it comes to enemy'ing someone, shouldn't it be a blanket relationship setter? If X is allied with Y (and vise versa in this case), and X enemies Y... does Y stay allied to X? That doesn't make a lot of sense. Allied should be per request, neutral from enemy should be per request, but enemy should blanket over.

**Comment by MarkehMe** [comment]
I do believe it is like this to stop abuse. But I can also see how this could also be abused.

I've introduced the enforced relations configuration option.

For example, if you set `ENEMY` in enforced relations to `true`:

If either faction A or B has enemy set. The relationship is set to ENEMY. So if they don't want to be enemies, they have to **both** unset to. But to be enemies **either** can set it.

**Comment by MarkehMe** [comment]
Heres an extract from the config. What do you think of the explanation? 😄 

```js
  
  /*
   * Relationships require both sides to set the relationship. If you want certaion relationships to automatically be enforced, set it here.
   * A better way to understand this, if you set enemy to true and either has enemy set - then enemy will be the enforced relation.
   */
  "enforcedRelations": {
    "ENEMY": false
  },
  
```
