### ISSUE TITLE
/f map updating

### ISSUE THREAD

**Issue by Gertius** [redstone/LegacyFactions#243]
When you type /f map, then teleport (for example /spawn), the /f map command shows the map of your old location - until you move chunk. Could this be changed so you don't have to move chunk please?

**Comment by Gertius** [comment]
Version

`14.10 06:00:25 [Server] INFO This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`

/f debug
`14.10 06:01:19 [Server] INFO === START DEBUG ===
14.10 06:01:19 [Server] INFO ----- Server Information -----
14.10 06:01:19 [Server] INFO Server Version: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
14.10 06:01:19 [Server] INFO LegacyFactions v1.4.7
14.10 06:01:19 [Server] INFO Package: package java.lang, Java Platform API Specification, version 1.8
14.10 06:01:19 [Server] INFO Java Version: 1.8.0_131
14.10 06:01:19 [Server] INFO ----- Plugins -----
14.10 06:01:19 [Server] INFO WorldBorder v1.8.7 by Brettflan
14.10 06:01:19 [Server] INFO Permissions v3.0 by wea_ondara
14.10 06:01:19 [Server] INFO HolographicDisplays v2.2.6 by 
14.10 06:01:19 [Server] INFO Essentials v2.0.1-b531 by Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, md678685
14.10 06:01:19 [Server] INFO EssentialsSpawn v2.0.1-b531 by Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits
14.10 06:01:19 [Server] INFO EssentialsChat v2.0.1-b531 by Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally
14.10 06:01:19 [Server] INFO PlaceholderAPI v2.8.2 by [extended_clip]
14.10 06:01:19 [Server] INFO EssentialsAntiBuild v2.0.1-b531 by Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, Iaccidentally
14.10 06:01:19 [Server] INFO LegacyFactions v1.4.7 by Cayorion, Madus, Ulumulu1510, MarkehMe, Brettflan, drtshock
14.10 06:01:19 [Server] INFO DeluxeMenus v1.10.1 by extended_clip
14.10 06:01:19 [Server] INFO ----- Integrations -----
14.10 06:01:19 [Server] INFO Essentials = true
14.10 06:01:19 [Server] INFO Metrics = true
14.10 06:01:19 [Server] INFO bStats = true
14.10 06:01:19 [Server] INFO === END DEBUG ===`

**Comment by MarkehMe** [comment]
Hello! 😄  

This is a friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf` file! Put it on www.pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks**

*This is an automatic message! Please respond saying you have done these things.*

**Comment by Gertius** [comment]
done - check above

**Comment by MarkehMe** [comment]
Fixed in 1.5.0 🎉 

###### (if you reported this as apart of our bounties program please message me on discord)
