### ISSUE TITLE
Language and Tag Parsing Issue

### ISSUE THREAD

**Issue by UberPilot** [redstone/LegacyFactions#257]
Debug Output: https://pastebin.com/LMxbC4Jq
conf.json: https://pastebin.com/jU1GSdLj
Version: `This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`
Log: https://pastebin.com/ExAUCevE

It appears that some messages don't properly parse tags, such as the `Your faction does not have a home` message and the buttons on the help. 

Examples: https://imgur.com/a/6wcN1

This is on a fresh installation of LegacyFactions on a newly compiled version of spigot-1.8.8

**Comment by MarkehMe** [comment]
Hello! 😄  

This is a friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf` file! Put it on www.pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks**

*This is an automatic message! Please respond saying you have done these things.*

**Comment by UberPilot** [comment]
These things have been done.

**Comment by markhughes** [comment]
Known bug, thanks!
