### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by TheIronMinerLv** [redstone/LegacyFactions#258]
Hi, when I tried to compile, it threw such error:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\user1\Desktop\LegacyFactions\build.gradle' line: 78

* What went wrong:
A problem occurred evaluating root project 'LegacyFactions'.
> Could not resolve all files for configuration ':compile'.
   > Could not resolve mkremins:fanciful:0.4.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve mkremins:fanciful:0.4.0-SNAPSHOT.
         > Unable to load Maven meta-data from http://repo.stealthyone.com/content/groups/public/mkremins/fanciful/0.4.0-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'http://repo.stealthyone.com/content/groups/public/mkremins/fanciful/0.4.0-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'http://repo.stealthyone.com/content/groups/public/mkremins/fanciful/0.4.0-SNAPSHOT/maven-metadata.xml'.
                  > Connect to repo.stealthyone.com:80 [repo.stealthyone.com/149.56.118.96] failed: Connection timed out: connect
```

With stacktrace: https://pastebin.com/H3Fi5iGw

Java:
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) Client VM (build 25.144-b01, mixed mode, sharing)
```

Gradle:
```
Gradle 4.2.1

Build time:   2017-10-02 15:36:21 UTC
Revision:     a88ebd6be7840c2e59ae4782eb0f27fbe3405ddf

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Windows 10 10.0 x86
```

I would highly appreciate if you could help to fix this. Why do I need to compile? I need to test that MySQL support for a few things, maybe you could send me a compiled one, that would help too.

**Comment by markhughes** [comment]
Hello! 😄  

This is a friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf` file! Put it on www.pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks**

*This is an automatic message! Please respond saying you have done these things.*

**Comment by TheIronMinerLv** [comment]
Hello?

**Comment by markhughes** [comment]
Sadly stealthyone has taken down the repo for fanciful. This is part of #253

**Comment by TheIronMinerLv** [comment]
So what should I do to fix this?

**Comment by TheIronMinerLv** [comment]
?

**Comment by TheIronMinerLv** [comment]
@markhughes do I really need to make a new issue?

**Comment by markhughes** [comment]
No. As I said, this is apart of #253
