### ISSUE TITLE
Faction Claiming Isn't Working

### ISSUE THREAD

**Issue by TheCamoWaffle** [redstone/LegacyFactions#259]
Hi,
When I do /f claim [radius] it doesn't claim properly, for example when I did /f claim 3 It claimed like it did in the photo
![2017-11-14_21 09 35](https://user-images.githubusercontent.com/33668773/32799424-c6f411e8-c988-11e7-9477-3409fd19505b.png)

**Comment by markhughes** [comment]
Hello! 😄  

This is a friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf` file! Put it on www.pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks**

*This is an automatic message! Please respond saying you have done these things.*

**Comment by markhughes** [comment]
Hi, it says in the picture. You don’t have enough power.
