### ISSUE TITLE
Legacy Factions on a modded server

### ISSUE THREAD

**Issue by ArhamR** [redstone/LegacyFactions#261]
hi i need help i have a modded server with server miner it is a modded 1.7.10 and i am trying to setup modded factions on the server but the legacy factions plugin will not work whenever i do /f ?, /f help or /f h i get no response from the chat or the console no error no nothing it just does not work along side modded factions i have also setup modded survival and want the 2 to be in different worlds with the multiverse plugin.

plugins list:
https://cdn.discordapp.com/attachments/336429701839192067/381303705170870273/Capture.PNG

**Comment by markhughes** [comment]
Hello! 😄  

This is a friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf` file! Put it on www.pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks**

*This is an automatic message! Please respond saying you have done these things.*

**Comment by markhughes** [comment]
Provide the contents of /f debug - this gives us some helpful information about your server.

**Comment by ArhamR** [comment]
i cant the plugin does not work i mentioned that above that is what i need help with the plugin is not working

**Comment by markhughes** [comment]
Sorry I didn’t realise you meant the plugin isn’t loading. 

Can you give me your server startup log so we can see why it’s not starting up?

**Comment by ArhamR** [comment]
[2017-11-12-1.log](https://github.com/redstone/LegacyFactions/files/1493216/2017-11-12-1.log)

**Comment by markhughes** [comment]
It is trying to integrate with HolographicDisplays except the API methods are missing. Can you update HolographicDisplays?

**Comment by ArhamR** [comment]
still disabled after update idk y
[latest.log](https://github.com/redstone/LegacyFactions/files/1502653/latest.log)

**Comment by ArhamR** [comment]
also is it possible to make pre set factions?

**Comment by ArhamR** [comment]
@markhughes ??, plz help

**Comment by markhughes** [comment]
```
[22:50:48] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: Failed to remap class net.redstoneore.legacyfactions.flag.Flags
```

Please see:
https://github.com/redstone/LegacyFactions/wiki/Forge%2C-KCauldron%2C-Thermos%2C-etc#thermos-issue-classnotfoundexception-failed-to-remap-class
