### ISSUE TITLE
About compiling

### ISSUE THREAD

**Issue by TheIronMinerLv** [redstone/LegacyFactions#262]
My goal is to make Factions plugin to work in multiple dedicated servers with one database. Until now I've used FactionsUUID, then I saw that you've added a MySQL support.

I would like to test it to know how much I could achieve, BUT I CANNOT COMPILE IT.

P.S. Basically I want to split my Factions server into multiple servers with connected database, players would think that there are just multiple worlds. Of course I would need to fork this to connect commands via bungeecord etc., but I need at least to know how mysql would work, so please help!

**Comment by markhughes** [comment]
Hello! 😄  

This is a friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf` file! Put it on www.pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks**

*This is an automatic message! Please respond saying you have done these things.*

**Comment by TheIronMinerLv** [comment]
Not for this issue.

**Comment by markhughes** [comment]
Please don't open multiple issues.

This is apart of #253
