### ISSUE TITLE
LegacyFactions crashing server.

### ISSUE THREAD

**Issue by Xrey274** [redstone/LegacyFactions#88]
MarkehMe - 1. Here's the new log file - https://www.dropbox.com/s/zt302958mgzuxb7/2017-08-04-7.log?dl=0 2. Please don't close the threat after you read it, please wait for me to respond. 3. Removed all the plugin you told me to. Server still crashes..

**Comment by Spazzinq** [comment]
@Xrey274 Can you please post the crash file? The startup log tells us nothing useful

**Comment by MarkehMe** [comment]
It's being closed because you haven't provided information that points to LegacyFactions. 

As much as I want to, I can't help you unless you actually show me where LegacyFactions is causing this. 

Because no one else in 1.8 has had this issue it seems like a pretty isolated case

Can you start first by sharing:
- the crash log 
- your conf.json file 
- server type and version 

And try:
- renaming conf.json and starting the server 
- removing LegacyFactions and starting the server, please share this log for comparison

**Comment by MarkehMe** [comment]
Closing this as you opened another issue.
